### ISSUE TITLE
NC IAT is not detected

### ISSUE THREAD

**Issue by johnceci-m3** [rusefi/rusefi#1534] opened 2020-06-23 23:20 UTC
we have 4.95v on IAT which is clearly a wiring issue yet no IAT RED indicator

![image](https://user-images.githubusercontent.com/6987080/85476541-8a5fca00-b586-11ea-9599-70a655a79a68.png)

![image](https://user-images.githubusercontent.com/6987080/85476555-96e42280-b586-11ea-9841-217fec89aa01.png)

**Comment by rusefi** [comment] 2020-06-23 23:39
@mck1117 ?

**Comment by mck1117** [comment] 2020-06-23 23:56
and I assume you've rebooted the ECU since changing those settings?

**Comment by rusefi** [comment] 2020-06-24 00:12
@mck1117 yes 100% I was looking at this via teamviewer

**Comment by mck1117** [comment] 2020-07-25 21:04
did this ever get resolved?

**Comment by rusefillc** [comment] 2020-07-25 21:15
@mck1117 not to the best of my knowledge

**Comment by mck1117** [comment] 2020-07-28 21:20
@johnceci-m3 does this still reproduce for you? My "IAT failed" indicator comes on when I unplug it, so I'm not able to get this to happen.

**Comment by mck1117** [comment] 2021-03-14 21:11
No report of this happening again, closing.

**Closed by mck1117** 2021-03-14 21:11 UTC
