### ISSUE TITLE
1NZ Trigger problems (36-2/4-1)

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4901] opened 2022-12-17 06:45 UTC
https://rusefi.com/online/view.php?log=1126

when Cam sync is enabled, VVT1 angle goes crazy. Soon will have SD card trigger logs

**Comment by mck1117** [comment] 2022-12-17 07:56
is this hall sensors or VR sensors?

**Comment by ElDominio** [comment] 2022-12-17 15:07
VR since Toyota

**Comment by mck1117** [comment] 2023-01-03 10:07
duplicate of #4930?

**Closed by mck1117** 2023-01-03 10:07 UTC

**Comment by ElDominio** [comment] 2023-01-03 12:27
Correct but all data is here mistakenly, why are both closed now?
