### ISSUE TITLE
Burn on VE table stops engine

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2744] opened 2021-05-26 17:47 UTC
@Abricosvw reports that burn on VE table while engine is running causes engine to stall

**Comment by rusefillc** [comment] 2021-05-26 17:47
@Abricosvw please paste youtube link

**Comment by Abricosvw** [comment] 2021-05-26 18:23
https://youtu.be/0Jh2iLBG-J4

**Comment by mck1117** [comment] 2021-05-26 18:31
More detail please.

- does ecu still connect?
- LEDs?
- Did it actually save the settings?
- Which ecu?

**Comment by mck1117** [comment] 2021-05-30 17:56
@Abricosvw ?

**Comment by Abricosvw** [comment] 2021-06-20 16:15
@rusefillc @andreika-git @dron0gus @mck1117 
https://youtu.be/bggwrzeQhsE

**Comment by mck1117** [comment] 2021-06-21 03:05
dupe of #2839

**Closed by mck1117** 2021-06-21 03:05 UTC
Labels: bug
