### ISSUE TITLE
injection scheduling artifact

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1041] opened 2019-12-03 17:51 UTC
As of today we have different scheduling mechanisms between spark and fuel.

Spark (and aux) uses a better scheduling approach where each event is in charge of scheduling the next one

Fuel still uses per-cycle scheduling approach which looks funny in transitional states. On the one hand, we do not care since that's fuel - on the other hand we know how to improve things and make things more consistent.

**Comment by rusefi** [comment] 2019-12-03 17:52
![IMG_89701](https://user-images.githubusercontent.com/7377949/70075869-9c1e5780-15cb-11ea-833d-c88033ec8f90.jpg)

 See section 33.3s, 39.3s, 44.1s, 48.2s,51.4s etc.

[Injector issue.zip](https://github.com/rusefi/rusefi/files/3917924/Injector.issue.zip)

**Comment by rusefi** [comment] 2019-12-03 17:53
Maybe relevant maybe not video https://www.youtube.com/watch?v=oeq7oF9QIf0

**Comment by rusefi** [comment] 2019-12-03 17:53
See recent commit on #460 for how similar thing was improved for aux valuve

**Comment by mck1117** [comment] 2020-07-28 22:55
this is maybe a dupe of #1594

**Comment by mck1117** [comment] 2022-06-23 06:37
yeah, this is #1594

**Closed by mck1117** 2022-06-23 06:37 UTC
