### ISSUE TITLE
Target AFR table Y axis stuck at 0

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4826] opened 2022-11-26 03:15 UTC
When updating firmware, an issue was found where the Target AFR tables "dot" does not move up or down the y axis.  It is stuck at zero.  It will follow X axis as expected.  This causes autotune to work incorrectly.  

Below is screenshot where Y axis is MAP and should be near 100.

Old Firmware
snapshot_20221011_031129_hellenNA6_rusefi
New Firmware
snapshot_20221117_044339_hellenNA6_rusefi

Firmware downloaded from https://github.com/rusefi/rusefi/wiki/Hellen64-Miata-NA6-94

<img width="773" alt="image" src="https://user-images.githubusercontent.com/82395131/204070346-823964d9-a44a-4f2d-a0f2-462ceb49d695.png">

**Comment by BeerMoneyMotorsports** [comment] 2022-11-26 03:26
I confirmed that firmware that it has happened at some point between this _snapshot_20221011_031129_hellenNA6_rusefi_ and this _snapshot_20221109_195113_hellenNA6_rusefi_

**Comment by rusefillc** [comment] 2022-11-26 03:29
Does "fuel: target AFR" gauge work?

**Comment by BeerMoneyMotorsports** [comment] 2022-11-26 03:37
Reads 0

<img width="843" alt="image" src="https://user-images.githubusercontent.com/82395131/204071034-3b73a823-53c6-4781-8004-1158ea8d2b7d.png">

**Comment by mck1117** [comment] 2022-11-26 03:42
I disagree with that title change - the "fuel: target AFR" gauge does NOT have anything to do with TS rendering the dot on that table. The dot gets controlled by `afrTableYAxis`. BOTH fields seem to be broken, which isn't really surprising since they're set next to each other in code.

**Comment by rusefillc** [comment] 2022-11-26 03:56
@mck1117 looks like a lot of concurrent edits are happening

**Comment by BeerMoneyMotorsports** [comment] 2022-11-26 20:19
Quick bench test shows improvement.  I will confirm on the lemon.  
<img width="431" alt="image" src="https://user-images.githubusercontent.com/82395131/204107578-ec53dad1-5a47-4034-949c-d704039b9f04.png">

**Comment by rusefillc** [comment] 2022-11-26 20:32
@mck1117 do you by any chance understand what commit already in master has fixed what? because I do not. Was it https://github.com/rusefi/rusefi/commit/23698be5f869f4204242944026e7de036f39c57c or https://github.com/rusefi/rusefi/commit/55062b1ef6d35e7b9c9480520acc8d1b0513d9d0 or else?

**Comment by mck1117** [comment] 2022-11-26 22:57
It looks like somehow `fuel_computer_s* getLiveDataAddr()` was returning nullptr

**Comment by rusefillc** [comment] 2022-11-26 23:16
@mck1117 hold on, you do not know how exactly we have fixed that?

Damn :(

**Comment by rusefillc** [comment] 2022-11-27 14:45
Time to close at least this one in light of https://github.com/rusefi/rusefi/commit/2b51f3798b2dbbbb409e42d23871653d0d6f3f55 ?

**Comment by mck1117** [comment] 2022-11-27 14:49
> @mck1117 hold on, you do not know how exactly we have fixed that?

> Time to close at least this one in light of https://github.com/rusefi/rusefi/commit/2b51f3798b2dbbbb409e42d23871653d0d6f3f55 ?

I'd like to actually debug why it was failing the old way once I'm at a real desk. Currently at 35000 feet/535mph/somewhere over the southern tip of greenland, and unable to attach a debugger to the simulator/ECU and figure out what was actually wrong.

**Comment by rusefillc** [comment] 2022-11-27 14:55
that's a crowded place no way to focus!

![image](https://user-images.githubusercontent.com/48498823/204141760-c0bdd02c-ec01-4ae9-bcb2-8b3a34fa3adc.png)

**Comment by mck1117** [comment] 2022-11-27 14:59
The real problem is that the sim doesn't run on a mac ☹️

**Comment by rusefillc** [comment] 2022-11-27 15:05
you have JNI unit tests?

**Comment by rusefillc** [comment] 2022-11-27 15:06
Dad mode: https://github.com/rusefi/rusefi/issues/4843

**Comment by rusefillc** [comment] 2022-11-29 00:56
@mck1117 do you agree that it's time for a release?
@mck1117 do you agree that we shall close this prior to a release?

**Comment by mck1117** [comment] 2022-11-30 04:29
> I'd like to actually debug why it was failing the old way once I'm at a real desk.

HAHAHAHAHAHA

the problem is that the `fragments` array is constructed before the `fuelComputer` of `Engine` was set. So of course it's null.

**Closed by mck1117** 2022-11-30 04:29 UTC
Labels: bug, IMPORTANT
