### ISSUE TITLE
ETB to not PWM while engine is not running

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2274] opened 2021-02-03 16:37 UTC
* - we want stopped engine to be silent to facilitate bench testing of low volume stuff like coil spark
	 * - we want stopped engine to draw as little amps as possible

**Comment by rusefillc** [comment] 2021-02-03 16:40
ETB wine is a major distraction during bench testing, manually turning it on/off is is just too much hassle. Does not turning on/off also require ECU reboot? We really just need ETB to not PWM while not running engine.

**Comment by mck1117** [comment] 2021-02-04 20:17
this is a duplicate of #2087

**Closed** 2021-02-04 22:06 UTC
