### ISSUE TITLE
Engine will not crank

### ISSUE THREAD

**Issue by biggie254-1** [rusefi/rusefi#2470] opened 2021-03-17 14:25 UTC
Got a base file for a 190e M111 conversion. Have verified the wiring is ok with injector and ignition tests working correctly. Signal from camshaft sensor is received to the ECU but the injectors and coil packs will not fire on ignition. 

Could the error below be preventing the engine from cranking?

![C00576F0-FD81-4447-BEBF-96F460507355](https://user-images.githubusercontent.com/80836684/111483172-9e1b1400-8745-11eb-8102-cc33ef93407b.png)

**Comment by rusefillc** [comment] 2021-03-17 20:06
rusEFI does not have a base tune for M111 - we have a legacy tune which has worked for some legacy version of the software.

Latest software requires both ETB sensors to be configured, not an issue.

**Comment by rusefillc** [comment] 2021-03-17 20:07
@OrchardPerformance @mck1117 close as "won't fix"?

**Comment by mck1117** [comment] 2021-03-17 20:13
Closing as "not a bug". This is the intended behavior. On vehicles with electronic throttle, we require redundant sensors to be configured.

In turn, any fatal config error will inhibit starting the engine.

**Closed by mck1117** 2021-03-17 20:13 UTC
