### ISSUE TITLE
Ability to define "Injector outputs disable" as Injector DutyCyle% goes beyond hard-coded maximum value.

### ISSUE THREAD

**Issue by tmbryhn** [rusefi/rusefi#5560] opened 2023-09-10 10:58 UTC
Fuel injector outputs disables suddenly (fuel cut code = 10) as duty passes approx 96%, and won't re-enable until RPM has decreased below 550 rpm (re-sets fuel cut code to 0).

**Describe the solution you'd like**
Allow for the user to have the injector outputs remain active when duty approaches and goes beyond 100%.

Add variable:
"Maximum allowable Injector DutyCycle%".

Add setting:
"Disable injector outputs if Injector DutyCycle% > *Maximum allowable Injector DutyCycle%*" = True/False.

**Comment by rusefillc** [comment] 2023-09-10 17:51
Duplicate of #4798

**Closed by rusefillc** 2023-09-10 17:51 UTC
Labels: enhancement
