### ISSUE TITLE
[Feature Request ] Add VE/AFR tables to Alpha-N strategy

### ISSUE THREAD

**Issue by 125jdavis** [rusefi/rusefi#1455] opened 2020-05-19 15:49 UTC
Alpha-N fueling algorithm doesn't have VE table or target AFR table. Currently the user tunes by changing target PW values in the TPS/RPM table. Useability would be much better if the same VE/AFR fueling  tables from speed density were carried over to Alpha-N.

**Comment by rusefi** [comment] 2020-05-19 15:58
@125jdavis how would this work?

MAP and MAF works by applying the math of target AFR and VE over measured air. How do we get measured air in Alpha-N?

**Comment by 125jdavis** [comment] 2020-05-19 17:34
![DSC_0004](https://user-images.githubusercontent.com/24885463/82359006-53215a80-99d5-11ea-8b29-fb76f35c87d7.JPG)

Similar to Speed Density, but VE and Pressure get lumped together into the TPS term.

**Comment by mck1117** [comment] 2020-05-19 19:09
Is this a mostly-duplicate of #1299?

**Comment by 125jdavis** [comment] 2020-05-21 13:37
@mck1117 I think you would know best.

Updated equation for O2 mass = TPS * Baro Pressure * Displacement / (Gas Constant * Intake Temp)

**Comment by mck1117** [comment] 2020-05-21 21:51
Instead of using TPS directly, I think you want a "VE" value looked up from a table as a function of TPS and RPM.  So essentially the same as the speed density math, but with pressure removed, and VE looked up using TPS instead of MAP.

**Comment by andreika-git** [comment] 2020-05-22 19:33
> "VE" value looked up from a table as a function of TPS and RPM

And we already have it implemented:
![image](https://user-images.githubusercontent.com/15104768/82703269-3e1a2500-9c7c-11ea-9c84-521a86d0a775.png)

**Comment by rusefi** [comment] 2020-05-22 19:36
@OrchardPerformance can you please document and add TS tooltip?

**Comment by OrchardPerformance** [comment] 2020-05-24 02:57
I don't think this function is quite what is being meant. 
This function changes the fuel tables Y axis to TPS when in speed density mode. 
But only when "TPS Based" is selected as an option in the "VE auto tune" settings. 

What Matt is referring to is making the standard AlphaN mode have a fuel table in VE rather than Ms pulse width. 
Either way it is all covered in the other ticket.

**Closed** 2020-07-25 16:15 UTC
