### ISSUE TITLE
Missing ADC Pins for ADC3, PF port

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#785] opened 2019-05-04 19:07 UTC
Pins for 144 pin mcu, ADC3 missing in both code and TS

PF3 to PF10

**Comment by rusefi** [comment] 2019-05-04 20:06
multiple issues here actually
1) ADC channels are hard-coded
```
// is there a reason to have this configurable?
#ifndef ADC_SLOW_DEVICE
#define ADC_SLOW_DEVICE ADCD1
#endif /* ADC_SLOW_DEVICE */

// is there a reason to have this configurable?
#ifndef ADC_FAST_DEVICE
#define ADC_FAST_DEVICE ADCD2
#endif /* ADC_FAST_DEVICE */
```
2) even for hard-coded ADC channels we sometimes have two options for ADC input pin but rusEfi has only one option hard coded

First step of the change would probably be to switch from using "input channels" in configuration to using "brain pins" for input configuration

**Comment by rusefi** [comment] 2019-05-14 20:39
need custom compile with
-DSTM32_ADC_USE_ADC3=TRUE -DADC_SLOW_DEVICE=ADCD3 -DEFI_PIN_ADC9=GPIOF_3

maybe this would make channel9 PF3 work for CLT and IAT? if that would work we can go from there

See https://www.st.com/resource/en/datasheet/stm32f769ni.pdf

**Comment by mck1117** [comment] 2021-03-19 18:27
duplicate of #2238

**Closed by mck1117** 2021-03-19 18:27 UTC

**Comment by rusefillc** [comment] 2024-11-08 16:26
See also https://github.com/rusefi/rusefi/issues/3350
