### ISSUE TITLE
updater openblt does not work

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6757] opened 2024-07-30 15:58 UTC
simple updater does not work in openblt mode - looks like something wrong about working folder?

**Comment by rusefillc** [comment] 2024-07-31 20:15
![image](https://github.com/user-attachments/assets/df6c7276-513b-4c12-b571-eaae8ebcafca)

**Comment by rusefillc** [comment] 2024-07-31 20:17
![image](https://github.com/user-attachments/assets/2902ef72-c73d-458e-9df1-f51ac12faca3)

**Comment by kifir23917** [comment] 2024-08-14 16:29
I cannot reproduce this issue, but I suspect that it relates to [the comment](https://github.com/rusefi/rusefi/issues/6788#issuecomment-2288759852) and will be fixed in the scope of #6788.
Let's return to this ticket if we reproduce something similar again.

**Closed** 2024-08-14 16:33 UTC
Labels: bug, java, console
