### ISSUE TITLE
temporary disable Acceleration enrichment logic for a few seconds After rpm Hard Limit event

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#413] opened 2017-05-11 23:14 UTC
If we hit a hard RPM limit we should disable Acceleration enrichment logic for a few seconds just to reduce the firmware confusion in case of RPM hard limit jerking

**Comment by rusefi** [comment] 2017-05-11 23:14
engineConfiguration->noAccelAfterHardLimitPeriodSecs

**Comment by mck1117** [comment] 2021-01-03 06:46
this is a dupe of #187

**Closed** 2021-01-03 06:51 UTC
