### ISSUE TITLE
Proteus f7 firmware compile fails, vw_b6.lua, 8000 bytes from string of 1073

### ISSUE THREAD

**Issue by biohazardav** [rusefi/rusefi#5413] opened 2023-07-18 18:50 UTC
During compilation of Proteus f7 firmware, compiler stops, log output shows vw_b6.lua warning "strncpy truncated copying 8000 bytes from a string of length 10731 [-Wstringgop-truncation] 

**Hardware**
 - Board: PROTEUS_STM32F7
 - Engine info: EZ30

**To Reproduce**
download master, attempt to compile with proteus selected as board and CPU set to ARCH_STM32F7

**Expected behavior**
successful compilation of F7 proteus bin. 

**Additional context**
I attempted a couple workarounds such as not treating warnings as errors being disabled, which successfully compiled and board appeared to function but was unsuccessful at communication with console or tunerstudio. Appears the problem affects the pages sent from the board and the generated ini does not fix this.

**Comment by mck1117** [comment] 2023-07-18 18:52
did you run `./gen_config_board.sh` for your board first?

**Comment by biohazardav** [comment] 2023-07-18 19:07
I just attempted after your reply this was the output of gen_config_board.sh:

`cyrax@DESKTOP-JKUDFGM /cygdrive/c/rusefi/rusefi/firmware
$ ./gen_config_board.sh proteus
Reusing configuration cache.

BUILD SUCCESSFUL in 6s
19 actionable tasks: 5 executed, 14 up-to-date
Configuration cache entry reused.
This script reads rusefi_config.txt and produces firmware persistent configuration headers
the storage section of rusefiXXX.ini is updated as well
BOARD_DIR=proteus SHORT_BOARDNAME=
Generating signature for
cat: proteus/prepend.txt: No such file or directory
BOARD_SPECIFIC_URL=[] for [] from [proteus]
BOARD_SPECIFIC_URL=[https://rusefi.com/s/wiki]
Using COMMON_GEN_CONFIG [
 -readfile OUTPUTS_SECTION_FROM_FILE console/binary/generated/output_channels.ini  -readfile DATALOG_SECTION_FROM_FILE console/binary/generated/data_logs.ini  -readfile LIVE_DATA_MENU_FROM_FILE console/binary/generated/fancy_menu.ini  -readfile LIVE_DATA_PANELS_FROM_FILE console/binary/generated/fancy_content.ini  -readfile LIVE_DATA_GAUGES_FROM_FILE console/binary/generated/gauges.ini  -ts_destination tunerstudio  -triggerInputFolder ../unit_tests  -with_c_defines false  -field_lookup_file controllers/lua/generated/value_lookup_generated.cpp controllers/lua/generated/value_lookup_generated.md  -java_destination ../java_console/models/src/main/java/com/rusefi/config/generated/Fields.java  -initialize_to_zero false  -signature tunerstudio/generated/signature_.txt  -signature_destination controllers/generated/signature_.h  -ts_output_name generated/rusefi_.ini  -prepend integration/rusefi_config_trigger.txt  -prepend proteus/prepend.txt  -board proteus]
class com.rusefi.ConfigDefinition Invoked with [-enumInputFile, controllers/algo/engine_types.h, -enumInputFile, controllers/algo/rusefi_enums.h, -definition, integration/rusefi_config.txt, -firing_order, controllers/algo/firing_order.h, -prepend, console/binary/generated/total_live_data_generated.h, -prepend, integration/rusefi_config_shared.txt, -tool, gen_config.sh, -readfile, OUTPUTS_SECTION_FROM_FILE, console/binary/generated/output_channels.ini, -readfile, DATALOG_SECTION_FROM_FILE, console/binary/generated/data_logs.ini, -readfile, LIVE_DATA_MENU_FROM_FILE, console/binary/generated/fancy_menu.ini, -readfile, LIVE_DATA_PANELS_FROM_FILE, console/binary/generated/fancy_content.ini, -readfile, LIVE_DATA_GAUGES_FROM_FILE, console/binary/generated/gauges.ini, -ts_destination, tunerstudio, -triggerInputFolder, ../unit_tests, -with_c_defines, false, -field_lookup_file, controllers/lua/generated/value_lookup_generated.cpp, controllers/lua/generated/value_lookup_generated.md, -java_destination, ../java_console/models/src/main/java/com/rusefi/config/generated/Fields.java, -initialize_to_zero, false, -signature, tunerstudio/generated/signature_.txt, -signature_destination, controllers/generated/signature_.h, -ts_output_name, generated/rusefi_.ini, -prepend, integration/rusefi_config_trigger.txt, -prepend, proteus/prepend.txt, -board, proteus, -enumInputFile, controllers/algo/rusefi_hw_enums.h, -c_defines, controllers/generated/rusefi_generated.h, -c_destination, controllers/generated/engine_configuration_generated_structures.h]
Opening logs/gen_config_.log
Reading firing from controllers/algo/firing_order.h
                field = "Ignition Output 2",                       ignitionPins2, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 2) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 2) || (firingOrder == 7) || (firingOrder == 9) || (firingOrder == 11) || (firingOrder == 12) || (firingOrder == 16) || (firingOrder == 19) || (firingOrder == 20) || (firingOrder == 23) || (firingOrder == 25) || (firingOrder == 29)))}
                field = "Ignition Output 3",                       ignitionPins3, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 3) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 1) || (firingOrder == 3) || (firingOrder == 4) || (firingOrder == 5) || (firingOrder == 9) || (firingOrder == 13) || (firingOrder == 14) || (firingOrder == 15) || (firingOrder == 18) || (firingOrder == 20) || (firingOrder == 23) || (firingOrder == 25) || (firingOrder == 27) || (firingOrder == 28)))}
                field = "Ignition Output 4",                       ignitionPins4, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 4) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 5) || (firingOrder == 7) || (firingOrder == 12) || (firingOrder == 14) || (firingOrder == 16) || (firingOrder == 17) || (firingOrder == 22) || (firingOrder == 23) || (firingOrder == 25) || (firingOrder == 26) || (firingOrder == 27) || (firingOrder == 31)))}
                field = "Ignition Output 5",                       ignitionPins5, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 5) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 4) || (firingOrder == 12) || (firingOrder == 15) || (firingOrder == 18) || (firingOrder == 23) || (firingOrder == 26) || (firingOrder == 30) || (firingOrder == 31)))}
                field = "Ignition Output 6",                       ignitionPins6, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 6) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 13) || (firingOrder == 22) || (firingOrder == 23) || (firingOrder == 29) || (firingOrder == 30)))}
                field = "Ignition Output 7",                       ignitionPins7, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 7) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 11) || (firingOrder == 15) || (firingOrder == 16) || (firingOrder == 19) || (firingOrder == 20) || (firingOrder == 22) || (firingOrder == 28)))}
                field = "Ignition Output 8",                       ignitionPins8, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 8) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 5) || (firingOrder == 11) || (firingOrder == 16) || (firingOrder == 18) || (firingOrder == 19) || (firingOrder == 26) || (firingOrder == 28)))}
                field = "Ignition Output 9",                       ignitionPins9, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 9) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 14) || (firingOrder == 15) || (firingOrder == 22)))}
                field = "Ignition Output 10",                       ignitionPins10, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 10) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 14) || (firingOrder == 16) || (firingOrder == 18)))}
                field = "Ignition Output 11",                       ignitionPins11, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 11) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 15)))}
                field = "Ignition Output 12",                       ignitionPins12, {isIgnitionEnabled == 1 && (ignitionMode != 0 && cylindersCount >= 12) && (ignitionMode !=2 || twoWireBatchIgnition == 1 || ((firingOrder == 18) || (firingOrder == 22)))}
Reading ../unit_tests\triggers.txt
Processing TRIGGERTYPE 1 10 TT_FORD_ASPIRE 0.00 1
id=1, count=10, name=TT_FORD_ASPIRE
onWheel TT_FORD_ASPIRE
Processing TRIGGERTYPE 2 32 TT_DODGE_NEON_1995 279.00 2
id=2, count=32, name=TT_DODGE_NEON_1995
onWheel TT_DODGE_NEON_1995
Processing TRIGGERTYPE 3 12 TT_MAZDA_MIATA_NA 5.18 3
id=3, count=12, name=TT_MAZDA_MIATA_NA
onWheel TT_MAZDA_MIATA_NA
Processing TRIGGERTYPE 4 14 TT_VVT_FORD_COYOTE 0.00 4
id=4, count=14, name=TT_VVT_FORD_COYOTE
onWheel TT_VVT_FORD_COYOTE
Processing TRIGGERTYPE 5 28 TT_GM_7X 0.00 5
id=5, count=28, name=TT_GM_7X
onWheel TT_GM_7X
Processing TRIGGERTYPE 6 8 TT_DAIHATSU 0.00 6
id=6, count=8, name=TT_DAIHATSU
onWheel TT_DAIHATSU
Processing TRIGGERTYPE 7 8 TT_MAZDA_SOHC_4 0.00 7
id=7, count=8, name=TT_MAZDA_SOHC_4
onWheel TT_MAZDA_SOHC_4
Processing TRIGGERTYPE 8 116 TT_TOOTHED_WHEEL_60_2 0.00 8
id=8, count=116, name=TT_TOOTHED_WHEEL_60_2
onWheel TT_TOOTHED_WHEEL_60_2
Processing TRIGGERTYPE 9 70 TT_TOOTHED_WHEEL_36_1 0.00 9
id=9, count=70, name=TT_TOOTHED_WHEEL_36_1
onWheel TT_TOOTHED_WHEEL_36_1
Processing TRIGGERTYPE 10 12 TT_MERCEDES_2_SEGMENT 0.00 10
id=10, count=12, name=TT_MERCEDES_2_SEGMENT
onWheel TT_MERCEDES_2_SEGMENT
Processing TRIGGERTYPE 11 4 TT_UNUSED_11 0.00 11
id=11, count=4, name=TT_UNUSED_11
onWheel TT_UNUSED_11
Processing TRIGGERTYPE 12 120 TT_SUBARU_EZ30 240.00 12
id=12, count=120, name=TT_SUBARU_EZ30
onWheel TT_SUBARU_EZ30
Processing TRIGGERTYPE 13 12 TT_VVT_MAZDA_SKYACTIV 0.00 13
id=13, count=12, name=TT_VVT_MAZDA_SKYACTIV
onWheel TT_VVT_MAZDA_SKYACTIV
Processing TRIGGERTYPE 14 14 TT_DODGE_NEON_2003_CAM 496.00 14
id=14, count=14, name=TT_DODGE_NEON_2003_CAM
onWheel TT_DODGE_NEON_2003_CAM
Processing TRIGGERTYPE 15 10 TT_MAZDA_DOHC_1_4 137.12 15
id=15, count=10, name=TT_MAZDA_DOHC_1_4
onWheel TT_MAZDA_DOHC_1_4
Processing TRIGGERTYPE 16 4 TT_ONE_PLUS_ONE 0.00 16
id=16, count=4, name=TT_ONE_PLUS_ONE
onWheel TT_ONE_PLUS_ONE
Processing TRIGGERTYPE 17 6 TT_VVT_JZ 0.00 17
id=17, count=6, name=TT_VVT_JZ
onWheel TT_VVT_JZ
Processing TRIGGERTYPE 18 2 TT_ONE 0.00 18
id=18, count=2, name=TT_ONE
onWheel TT_ONE
Processing TRIGGERTYPE 19 34 TT_DODGE_RAM 0.00 19
id=19, count=34, name=TT_DODGE_RAM
onWheel TT_DODGE_RAM
Processing TRIGGERTYPE 20 232 TT_60_2_VW 0.00 20
id=20, count=232, name=TT_60_2_VW
onWheel TT_60_2_VW
Processing TRIGGERTYPE 21 88 TT_BENELLI_TRE 0.00 21
id=21, count=88, name=TT_BENELLI_TRE
onWheel TT_BENELLI_TRE
Processing TRIGGERTYPE 22 24 TT_DODGE_STRATUS 150.00 22
id=22, count=24, name=TT_DODGE_STRATUS
onWheel TT_DODGE_STRATUS
Processing TRIGGERTYPE 23 120 TT_36_2_2_2 0.00 23
id=23, count=120, name=TT_36_2_2_2
onWheel TT_36_2_2_2
Processing TRIGGERTYPE 24 8 TT_NISSAN_SR20VE 630.00 24
id=24, count=8, name=TT_NISSAN_SR20VE
onWheel TT_NISSAN_SR20VE
Processing TRIGGERTYPE 25 142 TT_2JZ_3_34 0.00 25
id=25, count=142, name=TT_2JZ_3_34
onWheel TT_2JZ_3_34
Processing TRIGGERTYPE 26 128 TT_ROVER_K 0.00 26
id=26, count=128, name=TT_ROVER_K
onWheel TT_ROVER_K
Processing TRIGGERTYPE 27 96 TT_GM_24x 50.00 27
id=27, count=96, name=TT_GM_24x
onWheel TT_GM_24x
Processing TRIGGERTYPE 28 54 TT_HONDA_CBR_600 470.00 28
id=28, count=54, name=TT_HONDA_CBR_600
onWheel TT_HONDA_CBR_600
Processing TRIGGERTYPE 29 4 TT_MITSU_4G9x_CAM 0.00 29
id=29, count=4, name=TT_MITSU_4G9x_CAM
onWheel TT_MITSU_4G9x_CAM
Processing TRIGGERTYPE 30 64 TT_CHRYSLER_NGC_36_2_2 0.00 30
id=30, count=64, name=TT_CHRYSLER_NGC_36_2_2
onWheel TT_CHRYSLER_NGC_36_2_2
Processing TRIGGERTYPE 31 10 TT_3_1_CAM 0.00 31
id=31, count=10, name=TT_3_1_CAM
onWheel TT_3_1_CAM
Processing TRIGGERTYPE 32 14 TT_DODGE_NEON_2003_CRANK 496.00 32
id=32, count=14, name=TT_DODGE_NEON_2003_CRANK
onWheel TT_DODGE_NEON_2003_CRANK
Processing TRIGGERTYPE 33 16 TT_MIATA_VVT 715.00 33
id=33, count=16, name=TT_MIATA_VVT
onWheel TT_MIATA_VVT
Processing TRIGGERTYPE 34 4 TT_MITSU_4G63_CAM 0.00 34
id=34, count=4, name=TT_MITSU_4G63_CAM
onWheel TT_MITSU_4G63_CAM
Processing TRIGGERTYPE 35 22 TT_MAZDA_MIATA_VVT_TEST 276.00 35
id=35, count=22, name=TT_MAZDA_MIATA_VVT_TEST
onWheel TT_MAZDA_MIATA_VVT_TEST
Processing TRIGGERTYPE 36 38 TT_SUBARU_7_6 520.00 36
id=36, count=38, name=TT_SUBARU_7_6
onWheel TT_SUBARU_7_6
Processing TRIGGERTYPE 37 50 TT_JEEP_18_2_2_2 581.00 37
id=37, count=50, name=TT_JEEP_18_2_2_2
onWheel TT_JEEP_18_2_2_2
Processing TRIGGERTYPE 38 48 TT_12_TOOTH_CRANK 0.00 38
id=38, count=48, name=TT_12_TOOTH_CRANK
onWheel TT_12_TOOTH_CRANK
Processing TRIGGERTYPE 39 32 TT_DODGE_NEON_1995_ONLY_CRANK 279.00 39
id=39, count=32, name=TT_DODGE_NEON_1995_ONLY_CRANK
onWheel TT_DODGE_NEON_1995_ONLY_CRANK
Processing TRIGGERTYPE 40 34 TT_JEEP_4_CYL 484.00 40
id=40, count=34, name=TT_JEEP_4_CYL
onWheel TT_JEEP_4_CYL
Processing TRIGGERTYPE 41 4 TT_FIAT_IAW_P8 60.00 41
id=41, count=4, name=TT_FIAT_IAW_P8
onWheel TT_FIAT_IAW_P8
Processing TRIGGERTYPE 42 10 TT_FORD_ST170 0.00 42
id=42, count=10, name=TT_FORD_ST170
onWheel TT_FORD_ST170
Processing TRIGGERTYPE 43 6 TT_VVT_MIATA_NB 0.00 43
id=43, count=6, name=TT_VVT_MIATA_NB
onWheel TT_VVT_MIATA_NB
Processing TRIGGERTYPE 44 168 TT_RENIX_44_2_2 0.00 44
id=44, count=168, name=TT_RENIX_44_2_2
onWheel TT_RENIX_44_2_2
Processing TRIGGERTYPE 45 252 TT_RENIX_66_2_2_2 0.00 45
id=45, count=252, name=TT_RENIX_66_2_2_2
onWheel TT_RENIX_66_2_2_2
Processing TRIGGERTYPE 46 52 TT_HONDA_K_CRANK_12_1 0.00 46
id=46, count=52, name=TT_HONDA_K_CRANK_12_1
onWheel TT_HONDA_K_CRANK_12_1
Processing TRIGGERTYPE 47 8 TT_VVT_BOSCH_QUICK_START 0.00 47
id=47, count=8, name=TT_VVT_BOSCH_QUICK_START
onWheel TT_VVT_BOSCH_QUICK_START
Processing TRIGGERTYPE 48 68 TT_TOOTHED_WHEEL_36_2 0.00 48
id=48, count=68, name=TT_TOOTHED_WHEEL_36_2
onWheel TT_TOOTHED_WHEEL_36_2
Processing TRIGGERTYPE 49 50 TT_SUBARU_SVX 690.00 49
id=49, count=50, name=TT_SUBARU_SVX
onWheel TT_SUBARU_SVX
Processing TRIGGERTYPE 50 34 TT_1_16 0.00 50
id=50, count=34, name=TT_1_16
onWheel TT_1_16
Processing TRIGGERTYPE 51 14 TT_SUBARU_7_WITHOUT_6 520.00 51
id=51, count=14, name=TT_SUBARU_7_WITHOUT_6
onWheel TT_SUBARU_7_WITHOUT_6
Processing TRIGGERTYPE 52 20 TT_NISSAN_MR18_CAM_VVT 0.00 52
id=52, count=20, name=TT_NISSAN_MR18_CAM_VVT
onWheel TT_NISSAN_MR18_CAM_VVT
Processing TRIGGERTYPE 53 544 TT_TRI_TACH 0.00 53
id=53, count=544, name=TT_TRI_TACH
onWheel TT_TRI_TACH
Processing TRIGGERTYPE 54 110 TT_GM_60_2_2_2 0.00 54
id=54, count=110, name=TT_GM_60_2_2_2
onWheel TT_GM_60_2_2_2
Processing TRIGGERTYPE 55 12 TT_SKODA_FAVORIT 134.00 55
id=55, count=12, name=TT_SKODA_FAVORIT
onWheel TT_SKODA_FAVORIT
Processing TRIGGERTYPE 56 8 TT_VVT_BARRA_3_PLUS_1 0.00 56
id=56, count=8, name=TT_VVT_BARRA_3_PLUS_1
onWheel TT_VVT_BARRA_3_PLUS_1
Processing TRIGGERTYPE 57 72 TT_KAWA_KX450F 0.00 57
id=57, count=72, name=TT_KAWA_KX450F
onWheel TT_KAWA_KX450F
Processing TRIGGERTYPE 58 120 TT_NISSAN_VQ35 675.00 58
id=58, count=120, name=TT_NISSAN_VQ35
onWheel TT_NISSAN_VQ35
Processing TRIGGERTYPE 59 12 TT_VVT_NISSAN_VQ35 0.00 59
id=59, count=12, name=TT_VVT_NISSAN_VQ35
onWheel TT_VVT_NISSAN_VQ35
Processing TRIGGERTYPE 60 42 TT_NISSAN_VQ30 120.00 60
id=60, count=42, name=TT_NISSAN_VQ30
onWheel TT_NISSAN_VQ30
Processing TRIGGERTYPE 61 128 TT_NISSAN_QR25 585.00 61
id=61, count=128, name=TT_NISSAN_QR25
onWheel TT_NISSAN_QR25
Processing TRIGGERTYPE 62 16 TT_VVT_MITSUBISHI_3A92 0.00 62
id=62, count=16, name=TT_VVT_MITSUBISHI_3A92
onWheel TT_VVT_MITSUBISHI_3A92
Processing TRIGGERTYPE 63 50 TT_SUBARU_SVX_CRANK_1 690.00 63
id=63, count=50, name=TT_SUBARU_SVX_CRANK_1
onWheel TT_SUBARU_SVX_CRANK_1
Processing TRIGGERTYPE 64 50 TT_SUBARU_SVX_CAM_VVT 690.00 64
id=64, count=50, name=TT_SUBARU_SVX_CAM_VVT
onWheel TT_SUBARU_SVX_CAM_VVT
Processing TRIGGERTYPE 65 16 TT_FORD_TFI_PIP 662.50 65
id=65, count=16, name=TT_FORD_TFI_PIP
onWheel TT_FORD_TFI_PIP
Processing TRIGGERTYPE 66 10 TT_SUZUKI_G13B 0.00 66
id=66, count=10, name=TT_SUZUKI_G13B
onWheel TT_SUZUKI_G13B
Processing TRIGGERTYPE 67 10 TT_HONDA_K_CAM_4_1 0.00 67
id=67, count=10, name=TT_HONDA_K_CAM_4_1
onWheel TT_HONDA_K_CAM_4_1
Processing TRIGGERTYPE 68 128 TT_NISSAN_MR18_CRANK 80.00 68
id=68, count=128, name=TT_NISSAN_MR18_CRANK
onWheel TT_NISSAN_MR18_CRANK
Processing TRIGGERTYPE 69 60 TT_TOOTHED_WHEEL_32_2 0.00 69
id=69, count=60, name=TT_TOOTHED_WHEEL_32_2
onWheel TT_TOOTHED_WHEEL_32_2
Processing TRIGGERTYPE 70 132 TT_36_2_1 90.00 70
id=70, count=132, name=TT_36_2_1
onWheel TT_36_2_1
Processing TRIGGERTYPE 71 128 TT_36_2_1_1 90.00 71
id=71, count=128, name=TT_36_2_1_1
onWheel TT_36_2_1_1
Processing TRIGGERTYPE 72 128 TT_VVT_MITSUBISHI_6G75 585.00 72
id=72, count=128, name=TT_VVT_MITSUBISHI_6G75
onWheel TT_VVT_MITSUBISHI_6G75
Processing TRIGGERTYPE 73 6 TT_VVT_TOYOTA_4_1 0.00 73
id=73, count=6, name=TT_VVT_TOYOTA_4_1
onWheel TT_VVT_TOYOTA_4_1
Processing TRIGGERTYPE 74 96 TT_GM_24x_2 48.00 74
id=74, count=96, name=TT_GM_24x_2
onWheel TT_GM_24x_2
Processing TRIGGERTYPE 75 4 TT_UNUSED_75 0.00 75
id=75, count=4, name=TT_UNUSED_75
onWheel TT_UNUSED_75
Processing TRIGGERTYPE 76 8 TT_MITSU_4G63_CRANK 0.00 76
id=76, count=8, name=TT_MITSU_4G63_CRANK
onWheel TT_MITSU_4G63_CRANK
Processing TRIGGERTYPE 77 4 TT_60DEG_TOOTH 60.00 77
id=77, count=4, name=TT_60DEG_TOOTH
onWheel TT_60DEG_TOOTH
Processing TRIGGERTYPE 78 4 TT_UNUSED_78 0.00 78
id=78, count=4, name=TT_UNUSED_78
onWheel TT_UNUSED_78
I 230718 130134.148 [main] FileSystemBoardInputsImpl - No yaml files in proteus/connectors
Writing C header to controllers/generated/engine_configuration_generated_structures.h
60 total enumsReader
CRC32 from integration/rusefi_config.txt = 1897486157
CRC32 from controllers/algo/firing_order.h = 2237520855
CRC32 from console/binary/generated/total_live_data_generated.h = 839786673
CRC32 from integration/rusefi_config_shared.txt = 938046265
CRC32 from console/binary/generated/output_channels.ini = 3231368428
CRC32 from console/binary/generated/data_logs.ini = 3912820838
CRC32 from console/binary/generated/fancy_menu.ini = 1242488084
CRC32 from console/binary/generated/fancy_content.ini = 1985170253
CRC32 from console/binary/generated/gauges.ini = 750585596
CRC32 from integration/rusefi_config_trigger.txt = 431987546
java.nio.file.NoSuchFileException: proteus\prepend.txt
java.nio.file.NoSuchFileException: proteus\prepend.txt
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at com.rusefi.IoUtil2.getCrc32(IoUtil2.java:36)
        at com.rusefi.IoUtil2.getCrc32(IoUtil2.java:52)
        at com.rusefi.ConfigDefinition.doJob(ConfigDefinition.java:168)
        at com.rusefi.ConfigDefinition.main(ConfigDefinition.java:52)
SystemOut Hook done for logs/gen_config_.log
`

**Comment by rusefillc** [comment] 2023-07-18 19:08
Over the phone I was attempting to ask to open https://github.com/rusefi/rusefi/issues and search for "lazy"

**Comment by rusefillc** [comment] 2023-07-18 19:09
Duplicate of https://github.com/rusefi/rusefi/issues/5225 which has manual instructions

**Closed by rusefillc** 2023-07-18 19:09 UTC

**Comment by rusefillc** [comment] 2023-07-18 19:10
Technically real question is "why would anyone need to compile while not contributing improvement or reporting issues"?

**Comment by biohazardav** [comment] 2023-07-18 19:26
I don't normally run into many issues compiling and my contributions are little because my only modification is to the init_tps.cpp because the code does not play nice with the accelerator pedals i often use. I can't contribute to code because i am not a experienced coder. I dont think my input would be as helpful as others. 

I understand your frustration, and i will not call you again. I understand this stuff can consume more time especially when people dont go through the proper channels for help or information and I am trying to do what i can do for the 4 or so current boards im running before asking for help.

**Comment by rusefillc** [comment] 2023-07-18 19:34
@biohazardav please help by document why do you need a custom init_tps.cpp not on this ticket
