### ISSUE TITLE
Trigger decoding issues (60-2)

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#1488] opened 2020-06-11 18:01 UTC
The last months, I have not made any firmware-versions running without trigger-issues.
The car just stops and throws trigger-errors.

I have a older firmware running without this problem.
The car also runs perfect with both Link-Ecu and oem ecu.

It makes no difference at all if I download firmware, build it, ICU vs Exti etc..

The code it usually throws are these:

CUSTOM_OBD_TRG_DECODING = 6035,
CUSTOM_SYNC_ERROR = 6036,
CUSTOM_SYNC_COUNT_MISMATCH = 6037,

The trigger-logger in TS keeps showing negative values,but I dont know if thats related.

I attach a fresh driving log from both the older firmware that works + one newer that engine stops and throws these errors.
Both are done today with debug set as trigger-counter

[Logs.zip](https://github.com/rusefi/rusefi/files/4766496/Logs.zip)
 

![javaw_ksPWRrN6vL](https://user-images.githubusercontent.com/9406140/84422350-31ef0b00-ac1d-11ea-8d12-152713b88afc.png)

I am not used to work with this logger, but it seems like 6036 are triggered first.

In firmware it seems to be related to some index, and use debug i3 channel.

The I3 looks very different between the working and non-working..

![javaw_keY2JxrsMD](https://user-images.githubusercontent.com/9406140/84428227-66b39000-ac26-11ea-97b2-88af39a82426.png)

**Comment by mck1117** [comment] 2020-06-12 01:22
what hardware/engine are these?

**Comment by mck1117** [comment] 2020-06-12 01:28
and how modified is the firmware? does it reproduce with 100% vanilla firmware from official bundle?

**Comment by rusefi** [comment] 2020-06-12 01:31
![image](https://user-images.githubusercontent.com/7377949/84455250-d9bf0580-ac2a-11ea-9d7f-c1f0d4d5353e.png)

AFR, fuel logs - do these look healthy? @OrchardPerformance

**Comment by 960** [comment] 2020-06-12 07:43
> what hardware/engine are these?

It's the A4 1.8t with the same old hardware I had all the time.

It makes no difference if I use the mre F7 bundle or try other build-settings/flags.

**Comment by mck1117** [comment] 2020-06-12 07:59
please share your configuration (TS debug package zip)

**Comment by 960** [comment] 2020-06-12 08:17
I'll try to get it done later.. This is the tune 

[Audi_A4.zip](https://github.com/rusefi/rusefi/files/4769568/Audi_A4.zip)

**Comment by 960** [comment] 2020-06-12 08:30
Also, it doesnt start again with just trying to start it in gear again, even if I drop rpm to 0.
I have to reduce speed enough to get the rpm down to around 1000 rpm for it to start

**Comment by 960** [comment] 2020-06-12 09:05
2020-06-12_11_02_56_146: EngineState: rpm=711 time=379 index=0: gap=3.697 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_147: EngineState: error: synchronizationPoint @ index 46 expected 116/0/0 got 25/0/0
2020-06-12_11_02_56_148: EngineState: rpm=711 time=379 index=0: gap=0.029 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_149: EngineState: rpm=711 time=379 index=0: gap=0.711 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_150: EngineState: rpm=711 time=379 index=0: gap=1.476 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_150: EngineState: Emulating position sensor(s). RPM=2000
2020-06-12_11_02_56_151: EngineState: rpm=711 time=379 index=0: gap=8.662 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_152: EngineState: BURN in 4ms
2020-06-12_11_02_56_152: EngineState: rpm=711 time=379 index=0: gap=0.995 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_153: EngineState: rpm=711 time=379 index=0: gap=1.000 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_153: EngineState: CRC32 response: BBC91656
2020-06-12_11_02_56_154: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_154: EngineState: rpm=711 time=379 index=0: gap=1.004 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_155: EngineState: rpm=711 time=379 index=0: gap=0.996 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_156: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_156: EngineState: rpm=711 time=379 index=0: gap=1.003 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_157: EngineState: rpm=711 time=379 index=0: gap=0.997 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_158: EngineState: rpm=711 time=379 index=0: gap=1.002 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_159: EngineState: rpm=711 time=379 index=0: gap=0.997 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_159: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_160: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_161: EngineState: rpm=711 time=379 index=0: gap=1.003 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_162: EngineState: rpm=711 time=379 index=0: gap=1.000 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_162: EngineState: rpm=711 time=379 index=0: gap=0.995 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_163: EngineState: rpm=711 time=379 index=0: gap=1.000 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_164: EngineState: rpm=711 time=379 index=0: gap=1.000 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_165: EngineState: rpm=711 time=379 index=0: gap=1.002 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_166: EngineState: rpm=711 time=379 index=0: gap=0.996 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_167: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_168: EngineState: rpm=711 time=379 index=0: gap=1.000 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_168: EngineState: rpm=711 time=379 index=0: gap=1.002 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_169: EngineState: rpm=711 time=379 index=0: gap=0.997 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_169: EngineState: rpm=711 time=379 index=0: gap=1.003 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_170: EngineState: rpm=711 time=379 index=0: gap=0.995 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_170: EngineState: rpm=711 time=379 index=0: gap=0.999 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_171: EngineState: rpm=711 time=379 index=0: gap=1.004 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_171: EngineState: rpm=711 time=379 index=0: gap=0.996 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_172: EngineState: rpm=711 time=379 index=0: gap=1.002 expected from 1.600 to 4.000 error=Yes
2020-06-12_11_02_56_172: EngineState: rpm=711 time=379 index=0: gap=1.993 expected from 1.600 to 4.000 error=Yes

**Comment by 960** [comment] 2020-06-12 09:17
It triggers the exact same codes in TS with simulator.

Firmware are the latest from bundle.

![javaw_bRsWBlT12G](https://user-images.githubusercontent.com/9406140/84486806-2db70200-ac9e-11ea-9672-6b7bc13c54fe.png)

**Comment by 960** [comment] 2020-06-12 09:21
It triggers the exact same codes in TS with simulator.

Firmware are the latest from MRE bundle.
Not sure what more I can provide that are relevant to the issue.

![javaw_bRsWBlT12G](https://user-images.githubusercontent.com/9406140/84487282-cfd6ea00-ac9e-11ea-940b-3d4e751f38fe.png)

**Comment by 960** [comment] 2020-06-12 13:45
Firmware from 15.04.20 runs without stopping.
Not sure exact date this issue started, but thats the version I have.

**Comment by rusefi** [comment] 2020-06-12 13:57
please try https://github.com/rusefi/rusefi/releases

https://github.com/rusefi/rusefi/releases/tag/20200507_cinco_de_mayo
https://github.com/rusefi/rusefi/releases/tag/20200513
https://github.com/rusefi/rusefi/releases/tag/20200522

**Comment by 960** [comment] 2020-06-12 14:50
I am not able to upload tunes to any of these versions.
It's just errors, Data write failed, TS hanging for long time etc..
Whats that??

**Comment by 960** [comment] 2020-06-12 19:12
Problem solved!! :-)
Just had a 2 hour drive without one single trigger-error.

Solution was to use files from 16.05.20, that was a partial update of the files from 23.04.20
(recall I didnt update them fully because some different bug)

**Comment by mck1117** [comment] 2020-06-12 19:13
so is there an actual bug somewhere? is there an official release that you see the issue on or not?

**Comment by rusefi** [comment] 2020-06-12 19:13
Well, reporting that 16.05.20 worked is not a solution.

**Comment by 960** [comment] 2020-06-12 19:16
There is a bug somewhere for sure..
I dont know what more I can provide for you to find it.

It's been there for a while, and I have tried all kind if build-flags and even build from bundle several times.

I think the issue loading tune to mcu was the reason I did a partial update of those files

**Comment by rusefi** [comment] 2020-06-12 19:21
Well, at the moment I see this iteration as overall negative value

1) "partial update" makes no sense to me
2) very poor steps to reproduce the problem and overall problem description

Let's please value my time and make more effort. A possible solution would be to compile each day version and report results for each day. For some days into the past we probably have GH artifacts? Just as an example - see artifacts attached to https://github.com/rusefi/rusefi/runs/703977011

**Comment by 960** [comment] 2020-06-12 19:26
This is the exact reason I stopped reporting issues..
It's just asking for lots of crap, even you know all the issues I have run into have turned out to be real.
The reply are a totally irelevant comment about unhealty AFR, and a request for a TS debug package..
Now I have two hours of logs with this pattern at debug I3

Lets please all value russians time, and waste our worthless time at compiling and reporting every day :-)

![javaw_phhpZfid2R](https://user-images.githubusercontent.com/9406140/84539181-3d146a80-acf3-11ea-9e38-90b42cecb4f6.png)

**Comment by mck1117** [comment] 2020-06-12 19:32
We can't help you until you can provide a report of how to reproduce this issue using:
1. official bundle
2. self stimulation

**Comment by 960** [comment] 2020-06-12 19:43
Yes, the errors trigger with bundle and simulator. 
Try with around 3000 or something.

The errors uploading tune, worst after flashing started between 23.04 - 16.05 I think.
With those vanilla packs, I couldnt get it loaded no matter. TS freezes so bad I needed Task Manager to shut it..

It's not you helping me, but me helping you.
I have found a solution that works for me.

**Comment by mck1117** [comment] 2020-06-12 19:49
So current bundle trips it with self stimulator?

**Comment by 960** [comment] 2020-06-12 21:44
Just had one running simulator at 3000 for a while.

At around 1000 Seconds it trips a row of 6036 and 6037.

![javaw_7A8cJHneEl](https://user-images.githubusercontent.com/9406140/84547217-6210d980-ad03-11ea-875e-2a2c4933c97b.png)

**Comment by 960** [comment] 2020-06-13 21:35
If you say this isnt a issue, we'll just close it.

I can keep the engine alive for a while at low steady rpm.
The thing that stops the engine right away are rpm acceleration.

I dont have any difference in firmware, and use the same config/outputchannels-struct.
Removing the additional files I have makes no difference.

I posted logs and tune.
I dont know what more explanation or additional information I can possible provide.

**Comment by rusefi** [comment] 2020-06-13 22:25
Stay tuned @mck1117 is investigating and at least some irregularities were observed

**Comment by rusefi** [comment] 2020-06-14 03:44
@mck1117 do we suspect that this is related to #1491?

**Comment by 960** [comment] 2020-06-14 14:14
Matts change made it run without trigger errors in simulator.
Not tested in car. Maybe later today..

**Comment by 960** [comment] 2020-06-14 19:28
Bad news.. Engine still stops.

![javaw_VHts0BiWHP](https://user-images.githubusercontent.com/9406140/84602198-e5f2cf00-ae85-11ea-9845-11b83563528c.png)

**Comment by rusefi** [comment] 2020-06-15 04:09
@mck1117 says "I think the complete bug was:
Events A and B are scheduled very close together, T+10 and T+15
At T+10, we interrupt and execute A, which takes 4us.
At T+14, we check if more events are in the past that should have executed, and there are not.  This takes 2us.
At T+16, we reschedule the timer for the next event, which happens to be in the past.  In this case, we actually schedule the timer for 100us in the future (T+116, because of lateDelay), instead of when the event should've occurred, 1us in the past."

**Comment by 960** [comment] 2020-06-15 10:55
I'll try it out with these changes.

I just remembered it has happened with the older firmware as well, but not often.

It always occure with fast RPM acceleration. 
For example in 1 or 2 gear, when boost kicks full.

**Comment by rusefi** [comment] 2020-06-18 12:56
"You should really have a look at TS config.
At later firmware versions, first upload of settings after flash are real broken.."

this is a sad example of sabotaging the process by throwing unrelated information on the ticket

this ticket should be ONLY about things related to Trigger decoding issues (60-2)

please create separate tickets for separate issues

**Comment by rusefi** [comment] 2020-06-18 13:01
#1491 is now merged into master, please try grab fresh logs with official build.

worst case we will wait for more tools to collect composite logs of your drive

**Comment by 960** [comment] 2020-06-18 18:55
> "You should really have a look at TS config.
> At later firmware versions, first upload of settings after flash are real broken.."
> 
> this is a sad example of sabotaging the process by throwing unrelated information on the ticket
> 
> this ticket should be ONLY about things related to Trigger decoding issues (60-2)
> 
> please create separate tickets for separate issues

I would say it's pretty relevant to be able to upload settings to your builds for me to test it.
It writes a little, throws errors, I have to reconnect, write a little more over and over.

Your AFR comment are far less relevant. Even your post about this beeing relevant are less relevant.
We both know I have ran into tons of bugs, and all of them have turned out to be real.
Still same story over and over with you attacking, dont belive it, and just complaining.
You should learn to be thankful when someone trying to help you.
You have helped me with one thing:
I used to feel bad about bullying the geeks back in school-days..
Thanks to you, I dont have those feelings anymore.. I did the right thing.

On Topic:
The issue are not solved, the changes makes no differences.
I just discovered with my old working firmware, this issue starts if I enable spi2 and cj125.
Seems like something are balancing at the edge of overflowing something.

The shape of debug f6 are different at the running ones and those who dies.

Also:
None of the firmwares are able to start if you toggle ignition in speed and starting it in gear again.
Seems like they dont handle the large rpm-acceleration..
You have to reduce speed enough in highest gear to get it to about 1000 rpm for it to start.
You can try this yourself.

**Comment by rusefi** [comment] 2020-06-18 20:10
Fresh logs were requested, user has responded with a wall of text. Closing issue.

**Closed by rusefi** 2020-06-18 20:10 UTC

**Comment by 960** [comment] 2020-07-02 21:51
I am not letting childish behavior keeping users from getting this fixed.
It's 100% for sure it's a firmware-bug.
It runs fine with ooem ecu, link ecu and same boards with speeduino.
I have even hooked up a max9926 to replace the tle8888, but it makes no difference.

You can see it clear at the below screenshot:

![javaw_HohxgqbpdU](https://user-images.githubusercontent.com/9406140/86411919-2cd22880-bcbe-11ea-8898-1fb549ed8500.png)

[2020-07-02_21.45.41.mlg.zip](https://github.com/rusefi/rusefi/files/4866784/2020-07-02_21.45.41.mlg.zip)

**Comment by mck1117** [comment] 2020-07-02 22:02
do you have a photo of the missing tooth on your flywheel?

**Comment by 960** [comment] 2020-07-02 22:17
It's at the crank inside engine.
Looks like this:

![chrome_RLNppAZPRJ](https://user-images.githubusercontent.com/9406140/86413811-82a8cf80-bcc2-11ea-954c-71554b636a5c.png)

**Comment by rusefi** [comment] 2020-07-02 23:31
It looks like we do not have enough logger speed to see gap for each tooth individually? Somehow we need better logs.

Maybe log fewer fields?

Maybe try "composite logs" in addition to normal logs? maybe logic analyzer? maybe wait until rusEFI console has better logging option. Maybe SD card logging with few fields? No idea how quick is SD card logging.

![image](https://user-images.githubusercontent.com/7377949/86417221-67c26500-bc9a-11ea-8b20-2ee010d98c10.png)

**Comment by 960** [comment] 2020-07-03 01:20
I'll test a little and see if I can get better resolution.

Would it be a idea with filters that limits the allowed tooth time compared to the previous?
Like a enum with level 1, 2 and 3  (25%, 50% and 75%) that can be set in ts

**Comment by 960** [comment] 2020-07-03 14:32
This has the best resolution I am able to get

[2020-07-03_16.17.14.mlg.zip](https://github.com/rusefi/rusefi/files/4870190/2020-07-03_16.17.14.mlg.zip)

**Comment by rusefi** [comment] 2020-07-03 14:39
I believe it's still not logging each tooth individually. I believe that at the moment we do not have a tool set to investigate this effectively.

![image](https://user-images.githubusercontent.com/7377949/86479096-7f8cfe00-bd19-11ea-891c-31018d6a7698.png)

**Comment by 960** [comment] 2020-07-03 14:42
No, I see that.

But its clearly because the event-count just keep on above the expected ?

**Comment by 960** [comment] 2020-07-03 14:47
This 0.3 width at count 1

![javaw_2tcCyY8OEm](https://user-images.githubusercontent.com/9406140/86479592-bf210d80-bd4c-11ea-9b8c-2e33f9ee1a51.png)

**Comment by 960** [comment] 2020-07-03 14:51
It keeps repeating in all logs instead of the tooth that should be 3

This value shows in tooth logger as well

![javaw_g53vqQvUXE](https://user-images.githubusercontent.com/9406140/86479899-45d5ea80-bd4d-11ea-81b9-32c0b232d625.png)

**Comment by rusefi** [comment] 2020-07-03 15:01
Related to #1563

**Comment by 960** [comment] 2020-07-03 15:32
This log shows it happening at idle even before the next sync?



![javaw_UkRSq6T2BR](https://user-images.githubusercontent.com/9406140/86482878-1d50ef00-bd53-11ea-8a7f-1bdbaaa92960.png)



[2020-07-03_16.17.14.mlg.zip](https://github.com/rusefi/rusefi/files/4870397/2020-07-03_16.17.14.mlg.zip)

**Comment by 960** [comment] 2020-07-04 12:55
What setting do I use to make it sync at cam instead?
I'll try that and see if the issue are still there

It's 60-2 and the quick-start wheel, but I can cut off some teeth if thats easier.

**Comment by rusefi** [comment] 2020-07-04 13:13
quick-start wheel still not supported
if cutting i would be cutting 60/2 down to 30/2

before any cutting do you have the any logic analyzer like the $10 eBay? can you hook it up to processed VR signal between TLE8888 and stm32?

**Comment by 960** [comment] 2020-07-04 14:31
Something like this :-)

![DSC_0051](https://user-images.githubusercontent.com/9406140/86514523-21dcdc80-be13-11ea-8d31-3120ba6bb325.JPG)

I'll go out and give it a try.
I got new boards on the way, so these are getting retired.
New ones are without the TLE8888, and got footprint for both SPC5 and stm. They should be working with o5e, re and speeduino :-)

**Comment by 960** [comment] 2020-07-04 15:10
Ok, here are a pulseview file from where it is stopping


[Stopping.zip](https://github.com/rusefi/rusefi/files/4873050/Stopping.zip)

**Comment by 960** [comment] 2020-07-04 15:47
The toothwidth of 0.3 are toothduration after missing tooth / toothduration for missing teeth..

![K26j91MXnp](https://user-images.githubusercontent.com/9406140/86516110-4b4f3580-be1e-11ea-8d9f-90dc402b7922.png)

**Comment by 960** [comment] 2020-07-04 23:28
Solution: Use chinese logic analyzer to read trigger signal? :-)

Each time this happen  index or eventcount keeps counting past the maximum 

![javaw_MHCxJY1jn5](https://user-images.githubusercontent.com/9406140/86522469-81140e80-be5e-11ea-885f-544ebe7bd571.png)

**Comment by rusefi** [comment] 2020-07-05 15:46
(i am a bit behind, I absolutely plan to look into this properly - that you for the data)

**Comment by 960** [comment] 2020-07-05 17:22
I think the issue are in this function

for (int i = 0;i<GAP_TRACKING_LENGTH;i++) {
				bool isGapCondition = cisnan(triggerShape->syncronizationRatioFrom[i]) || 
	(toothDurations[i] > toothDurations[i + 1] * triggerShape->syncronizationRatioFrom[i]
	&& toothDurations[i] < toothDurations[i + 1] * triggerShape->syncronizationRatioTo[i]);

				isSync &= isGapCondition;
The ratios are from 1.6 to 4 in Vw decoder.

Some places it pass 4. 

![pulseview_ZhL01OaMIP](https://user-images.githubusercontent.com/9406140/86538193-b9fec280-bef4-11ea-99b6-2b52313b99f1.png)

**Comment by mck1117** [comment] 2020-07-05 21:23
It's only looking at rising edges (in your case), so this is what it's measuring:
![image](https://user-images.githubusercontent.com/568254/86542480-eef61f80-beca-11ea-8a12-72fa18e72ae9.png)

B is expected to be 3 * A with an N-2 wheel.

**Comment by mck1117** [comment] 2020-07-05 21:24
It looks like it's about 3.1-3.2 * A in your snip, which is totally fine.

**Comment by 960** [comment] 2020-07-05 22:24
How hard would it be to add some cam signals to the decoder?

(In lack of other things to try :-) )

**Comment by mck1117** [comment] 2020-07-05 22:39
can you take a logic analyzer trace with both the crank signal AND the trigger error signal?  I want to see the exact instant the firmware decided something was wrong.

**Comment by 960** [comment] 2020-07-05 22:59
I can place some lines in code to turn a pin(or more) high or low while driving with analyzer connected.

Where in code do you want them?

Isnt that done just something like this?

```
if (xxxxxx) {
				enginePins.xxxxxx.setValue(1);
			}

```

**Comment by mck1117** [comment] 2020-07-06 00:29
![image](https://user-images.githubusercontent.com/568254/86545647-03471600-bee5-11ea-8801-2fa8edf07b88.png)

**Comment by 960** [comment] 2020-07-06 01:38
I have hooked up two extra wires, and it seems to work.
Going out to test tomorrow.

What rate are the minimum I can sample with?

**Comment by rusefi** [comment] 2020-07-06 02:08
I assume 1MHz would be just fine

**Comment by mck1117** [comment] 2020-07-06 03:14
yep, 1mhz is likely plenty

**Comment by 960** [comment] 2020-07-06 14:59
Pulseview session where it stops around 4.03

[Stopping.zip](https://github.com/rusefi/rusefi/files/4879678/Stopping.zip)

**Comment by 960** [comment] 2020-07-06 18:46
There are something strange about the tooth duration array.

I have logged toothduration[0] and toothduration[1] (just at bench), and the pattern are just as irregular


![javaw_bVFrpZZKYR](https://user-images.githubusercontent.com/9406140/86628146-c739b100-bfc9-11ea-81a7-034b52c88935.png)

**Comment by mck1117** [comment] 2020-07-06 19:00
Had a look at your pulseview session, and the trigger pattern looks fine.  I don't see anything that should've provoked the sync loss, which means that we got backed up on interrupts far enough to miss a tooth, which isn't great.  Are you running a release build?

The tooth durations look irregular because you aren't logging fast enough to catch every tooth, so they alias and you sometimes see long teeth, and sometimes see short teeth.

**Comment by 960** [comment] 2020-07-06 19:11
Ah, ok..
 
Yes, this build are very release. I tried removing all the text-logging to see if it made any change.

It's running like it's on steriods, but trigger-issue remains about the same (maybe a little better).
I have tried lots of changes and lots of firmwares.

Isnt these interrupts running at a separate tread or something? (I dont understand a lot of that)

![stm32cubeide_hGcNc1KTkN](https://user-images.githubusercontent.com/9406140/86629974-75def100-bfcc-11ea-8d8b-4b8e80b50fe4.png)

**Comment by 960** [comment] 2020-07-06 19:49
Would it help to use the cam for sync?

I dont understand the decoders completly, else I could just add the quick-start wheel to the decoder.

Does it still use the missing teeth?

**Comment by mck1117** [comment] 2020-07-06 20:08
It would still use the crank sensor as the primary, and the cam sensor just to resolve which "half" of the engine cycle was current, in addition to VVT phase.

**Comment by 960** [comment] 2020-07-06 20:24
Ok, I recently sold my TTLink to a customer in need, so I drive with this daily.
A bit annoying that it stops :-)

**Comment by mck1117** [comment] 2020-07-06 20:39
>  A bit annoying that it stops :-)
Just add more boost so that you don't need to go above 4000 rpm :joy:

**Comment by 960** [comment] 2020-07-06 20:42
Well, I noticed in some of the logs it passes 300 Kpa :-)

It's a GTX28R at a 1.8 engine, so both the rpm and boost are needed :-)

**Comment by 960** [comment] 2020-07-06 22:05
I'll order another TT-Link :-)

But it's a bit weird a 216 Mhz F7 cant read a 60-6 trigger?
Even the mcu's back in the stoneage did that..

**Comment by mck1117** [comment] 2020-07-06 22:08
> But it's a bit weird a 216 Mhz F7 cant read a 60-6 trigger?
> Even the mcu's back in the stoneage did that..

No ECU can decode 60-2 if there's a bug that causes it to sometimes lose teeth 🙂

My car raced all weekend on 60-2 with hours of total time above 4000 rpm, so I'm pretty sure it's some bug that happens to appear with whatever particular combination you have configured.

**Comment by mck1117** [comment] 2020-07-06 22:13
can you check with the rusefi console after sync loss? It should print some details about what it expected/what went wrong

**Comment by 960** [comment] 2020-07-06 22:32
Ah, so it's a bug :-)

Yeah, I can try to do that.. 
I am not a massive user of the console :-)

I can run high rpm without it stopping, but not high dRpm..

I guess you dont have enough rpm acceleration ;-)

**Comment by 960** [comment] 2020-07-06 23:01
But before a drastic console attempt, are there anywhere in the code the two pins (triggererror and debugsync) can be placed/moved to that could be informative?

**Comment by mck1117** [comment] 2020-07-06 23:03
I guess it wouldn't hurt to set/clear a pin whenever we're in the trigger interrupt.  Set a pin at the beginning of `hwHandleShaftSignal`, and clear it at the end.  If you can grab a log with trigger signal, that new signal, and the trigger error signal, that should shine a bit of light.

**Comment by 960** [comment] 2020-07-06 23:11
Inside this?


```
void hwHandleShaftSignal(trigger_event_e signal, efitick_t timestamp) {
	ScopePerf perf(PE::HandleShaftSignal);

#if EFI_TOOTH_LOGGER
		LogTriggerTooth(signal, timestamp PASS_ENGINE_PARAMETER_SUFFIX);
#endif /* EFI_TOOTH_LOGGER */

	if (!CONFIG(enableTriggerFilter)) {
		if (!isUsefulSignal(signal PASS_CONFIG_PARAMETER_SUFFIX)) {
			return;
		}
	}
	uint32_t triggerHandlerEntryTime = getTimeNowLowerNt();
	if (triggerReentraint > maxTriggerReentraint)
		maxTriggerReentraint = triggerReentraint;
	triggerReentraint++;

	efiAssertVoid(CUSTOM_ERR_6636, getCurrentRemainingStack() > 128, "lowstck#8");
	engine->triggerCentral.handleShaftSignal(signal, timestamp PASS_ENGINE_PARAMETER_SUFFIX);

	triggerReentraint--;
	triggerDuration = getTimeNowLowerNt() - triggerHandlerEntryTime;
	if (triggerDuration > triggerMaxDuration)
		triggerMaxDuration = triggerDuration;
}
```

**Comment by mck1117** [comment] 2020-07-06 23:13
Yep.  Set that pin to `1` at the beginning (near `ScopePerf perf(PE::HandleShaftSignal)`, and `0` at the end (near `triggerReentraint--`)

**Comment by 960** [comment] 2020-07-06 23:16
How can that show anything?

That would just be the rate it reads thru the function?

**Comment by mck1117** [comment] 2020-07-06 23:17
That's exactly what I'm interested in.

**Comment by mck1117** [comment] 2020-07-06 23:17
If we get a trigger error, it means that one or more of the preceeding teeth were missed - I want to see which one(s).

**Comment by 960** [comment] 2020-07-06 23:45
I dont understand how you can see that from the rate of that function :-)

But I'll do a test tomorrow :-)

I placed it after this:

triggerReentraint--;
	enginePins.debugTriggerSync.setValue(0);

**Comment by 960** [comment] 2020-07-07 09:19
Now this looks interesting whatever it shows :-)

Does it run thru those lines for each event?

![pulseview_a4CLkjGY0r](https://user-images.githubusercontent.com/9406140/86757619-90a07c80-c043-11ea-8344-f776d34a2dc6.png)


[interesting.zip](https://github.com/rusefi/rusefi/files/4883863/interesting.zip)

**Comment by 960** [comment] 2020-07-07 10:02
![msedge_imgPnGFX3T](https://user-images.githubusercontent.com/9406140/86765620-ad3fb300-c049-11ea-9252-bb93814d1ea6.png)
![msedge_yBFet0yCcK](https://user-images.githubusercontent.com/9406140/86765633-b3359400-c049-11ea-8f98-6aa6383b9c12.png)
![msedge_xP8Jj22RvA](https://user-images.githubusercontent.com/9406140/86765648-b7fa4800-c049-11ea-9635-de7456047579.png)

**Comment by 960** [comment] 2020-07-07 10:08
The gap should still be correct?

![Inkedpulseview_DPtPqX4UNJ_LI](https://user-images.githubusercontent.com/9406140/86766237-8c2b9200-c04a-11ea-9991-5c231cc5be1a.jpg)

**Comment by mck1117** [comment] 2020-07-07 18:10
wait, where did you put the pin set/clear statements? That doesn't look like what I expected

**Comment by 960** [comment] 2020-07-07 18:31
```
void hwHandleShaftSignal(trigger_event_e signal, efitick_t timestamp) {
	ScopePerf perf(PE::HandleShaftSignal);
	enginePins.debugTriggerSync.setValue(1);
#if EFI_TOOTH_LOGGER
		LogTriggerTooth(signal, timestamp PASS_ENGINE_PARAMETER_SUFFIX);
#endif /* EFI_TOOTH_LOGGER */

	if (!CONFIG(enableTriggerFilter)) {
		if (!isUsefulSignal(signal PASS_CONFIG_PARAMETER_SUFFIX)) {
			return;
		}
	}
	uint32_t triggerHandlerEntryTime = getTimeNowLowerNt();
	if (triggerReentraint > maxTriggerReentraint)
		maxTriggerReentraint = triggerReentraint;
	triggerReentraint++;

	efiAssertVoid(CUSTOM_ERR_6636, getCurrentRemainingStack() > 128, "lowstck#8");
	engine->triggerCentral.handleShaftSignal(signal, timestamp PASS_ENGINE_PARAMETER_SUFFIX);

	triggerReentraint--;
	enginePins.debugTriggerSync.setValue(0);
	triggerDuration = getTimeNowLowerNt() - triggerHandlerEntryTime;
	if (triggerDuration > triggerMaxDuration)
		triggerMaxDuration = triggerDuration;
}
```

**Comment by 960** [comment] 2020-07-07 18:35
I have no idea :-)

But whatever it shows seems to reflect whats happening..

**Comment by mck1117** [comment] 2020-07-07 18:37
Oops, you need a second `enginePins.debugTriggerSync.setValue(0);` just here:

![image](https://user-images.githubusercontent.com/568254/86826923-3523be00-c046-11ea-90ab-ce4d07636db9.png)

**Comment by 960** [comment] 2020-07-07 19:11
Now I have to cut down on tripping this.. It sounds real brutal, and this time it only ran at 3 cylinders for a while after it :-)

[new_abuse_audi.zip](https://github.com/rusefi/rusefi/files/4886710/new_abuse_audi.zip)

**Comment by mck1117** [comment] 2020-07-07 19:24
This interrupt was extremely late:
![image](https://user-images.githubusercontent.com/568254/86832200-b9793f80-c04c-11ea-9c24-6184c9758885.png)

**Comment by 960** [comment] 2020-07-07 19:43
What does this show compared to the other sample?

Are the tooth-width timestamps sampled at every event?
Not just the rising?

**Comment by mck1117** [comment] 2020-07-08 08:29
Currently an interrupt occurs on both the rising and falling edges, but we ignore falling edges, and only process the rising edge.  The circled event was an interrupt that was late - it happened around 65us after it should have.  In fact, it was so late that we thought the missing tooth happened early! (we only trigger sync error upon finding the sync point - missing tooth in this case).

**Comment by 960** [comment] 2020-07-09 11:13
Cant we make the missing tooth-check a little more clever/have some more factors?

The tooth-count are correct, and the missing tooth are at the correct place..

**Comment by 960** [comment] 2020-07-09 13:25
Or if we set the timestamps only at the rising edges it would be correct?

![pulseview_vJK25CtZsE](https://user-images.githubusercontent.com/9406140/87045495-41e81380-c1f8-11ea-8010-b1a6d18f8441.png)


![pulseview_6ib3e70vQR](https://user-images.githubusercontent.com/9406140/87045540-4dd3d580-c1f8-11ea-9cf0-868d3a4cda03.png)

**Comment by 960** [comment] 2020-07-09 18:43
Ok, I did a few small changes, and now I wasnt able to trip this error..


```

if (type == TV_RISE) {
	if (isFirstEvent) {
		currentDurationLong = 0;
	} else {
	currentDurationLong = nowNt - toothed_previous_time;
	}
}

if (type == TV_RISE) {
		toothed_previous_time = nowNt;
	}
```

![pulseview_L08h7pwXKk](https://user-images.githubusercontent.com/9406140/87078375-cea8c680-c224-11ea-947c-c5b83fa1fe2b.png)

**Comment by 960** [comment] 2020-07-18 21:24
A good tip if anyone runs into this is to turn off as much pwm outputs as possible..

It seems it helps a lot to turn off boost-control, gp-pwm etc..
Not sure why, but it seems related.
