### ISSUE TITLE
TPS calibration usability went down

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1204] opened 2020-03-21 01:31 UTC
TPS calibration usability went down with new sensor implementation

previously we were evaluating settings on each access, now we wait for Burn command and this dialog does not have a Burn button :(

I believe we have to revert back to behavior without A&B pre-calculation and just interpolate on each invocation

**Comment by mck1117** [comment] 2020-03-22 10:19
Just did some testing - this wasn't a regression in our firmware.  TS doesn't send the burn command, so we never copy the value from the working copy to the in-use one.  Either TS stopped sending the burn command (possible), or it never actually worked without pressing the burn button (also possible).

**Comment by mck1117** [comment] 2020-03-22 10:21
Hoooold on a sec - I just got TS to burn by pressing the "accept" button on the TPS dialog.  This is clearly a TS bug, not a bug in our firmware.

**Comment by mck1117** [comment] 2020-03-22 10:27
It seems like it's a dice roll whether it works or not.  I tried flipping back and forth between two values with the exact same sequence of mouse clicks/key presses, and it burned maybe half the time.

Confirmed by showing gauges with both the new and old TPS calculations, and a breakpoint in the `reconfigureTps()` function, that was only hit some of the times the "Accept" button was pressed.

**Comment by mck1117** [comment] 2020-03-22 10:38
Here's the behavior.  The first two worked as they should, but the third never burned after changing the setting.  Note how the burn button turns red when accept is clicked, and the new settings applied after burn is pressed.

https://www.youtube.com/watch?v=wGzJsUrX36A

**Comment by OrchardPerformance** [comment] 2020-05-22 17:24
Can confirm this is present but it seems to be a TS bug. 
Do we close as this is not a rusEFI problem and send a bug report to TS?

**Comment by rusefi** [comment] 2020-05-22 17:26
It would have to start open to keep state of TS bug and would be closed once we have a resolution from TS or else?

We can maybe consider hiding OEM TS dialog altogether for example - we have options?

**Comment by mck1117** [comment] 2021-05-31 06:40
This is fixed as of TS 3.1.04 or so.

**Closed by mck1117** 2021-05-31 06:40 UTC
Labels: bug
