### ISSUE TITLE
https://github.com/rusefi/rusefi/wiki/ was replaced with https://wiki.rusefi.com/ but is still existing => user confusion

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi#4749] opened 2022-11-07 20:37 UTC
maybe this is related to https://github.com/rusefi/rusefi_documentation/pull/205 ?

Currently its easy to get confused because https://github.com/rusefi/rusefi/wiki/ was replaced with https://wiki.rusefi.com/ but is still existing with partially outdated content

Another related issue is likely
![image](https://user-images.githubusercontent.com/22799428/200411337-efb40f55-9d16-4ed8-b954-12ea9379f534.png)

**Comment by rusefillc** [comment] 2022-11-08 00:06
Duplicate of https://github.com/rusefi/rusefi_documentation/issues/210

**Closed by rusefillc** 2022-11-08 00:06 UTC
